SPK_NAME = synocli-disk
SPK_VERS = 0.0.1
SPK_REV = 1
SPK_ICON = src/dar.png

DEPENDS = cross/dar cross/testdisk

MAINTAINER = spacifici
DESCRIPTION = Add a nice description here
STARTABLE = no
DISPLAY_NAME = SynoCli Disk
# CHANGELOG = ""

INSTALLER_SCRIPT = src/installer.sh
SSS_SCRIPT       = src/dsm-control.sh

HOMEPAGE = http://dar.linux.free.fr/
LICENSE  = GPLv2

INSTALL_PREFIX = /usr/local/synocli-disk

include ../../mk/spksrc.spk.mk
